[QOLDEV-22] add option to change download directory 2
qld-gov-au/seleniumHelper pull request #367
Opened 2023-02-23 05:57 UTC by RossWebsterWork

2023-03-02 22:48 UTC, ThrawnCA approved these changes

2023-03-03 03:39 UTC, duttonw approved these changes

2023-03-03 05:53 UTC, ThrawnCA approved these changes

2023-03-07 02:14 UTC, ThrawnCA approved these changes

2023-03-07 02:15 UTC, ThrawnCA commented
Build is broken.

2023-03-07 23:23 UTC, ThrawnCA approved these changes

2023-03-08 07:20 UTC, RossWebsterWork commented
With the test that is failing, it is set to download a test file from dev.data to a temporary location and then check that the file is there, before marking it to be deleted.

This works locally, but would downloading and checking files work on GitHub builds?

2023-03-08 23:29 UTC, ThrawnCA approved these changes

2023-03-08 23:30 UTC, ThrawnCA commented
> This works locally, but would downloading and checking files work on GitHub builds?

It should work the same way. The builds should still have access to a local disk.

2023-03-10 04:04 UTC, ThrawnCA commented
Looks okay but build is still failing...

2023-03-13 07:01 UTC, ThrawnCA approved these changes

2023-03-14 01:16 UTC, duttonw approved these changes

2023-03-14 01:45 UTC, ThrawnCA requested changes

2023-03-14 01:45 UTC, ThrawnCA commented on src/main/java/au/gov/qld/online/selenium/SeleniumHelper.java
> +            proxy.setHttpProxy(System.getProperty("http_proxy", "").replaceAll("http.*?://", ""));
This shouldn't use `.*`; it's too greedy, it might match more of the URL instead of just the protocol.

`https?://` would be better.

2023-03-14 04:38 UTC, closed without merging